import torch
from torch.nn import functional as F
from tokenizers import Tokenizer

from corpus import end_of_text
from model import Config, get_device, load_model


def generate(model, prompt = end_of_text):
    is_training = model.training

    device = get_device()

    model.eval()
    model.to(device)

    tokenizer = Tokenizer.from_file('../data/tokenizer.json')
    end_of_text_token = tokenizer.token_to_id(end_of_text)

    tokens = tokenizer.encode(prompt).ids
    tokens = torch.tensor(tokens, dtype = torch.long)
    tokens = tokens.unsqueeze(0)

    x = tokens.to(device) # The input to feed the model to (max size = context length)
    y = torch.tensor([], dtype = torch.long, device = device).view(1, 0) # The entire output generated by the model (can be longer than the context length)

    sample_rng = torch.Generator(device = device)
    sample_rng.manual_seed(torch.seed()) # Necessary, otherwise the ouput will always be the same

    config = Config()
    while y.size(1) < config.context_size * 10: # Stop generating, if the model won't
        with torch.no_grad():
            logits, _ = model(x)
            logits = logits[:, -1, :]

            probs = F.softmax(logits, dim = -1)

            # Top-K sampling
            topk_probs, topk_indices = torch.topk(probs, 50, dim = -1)
            ix = torch.multinomial(topk_probs, 1, generator = sample_rng)
            xcol = torch.gather(topk_indices, -1, ix)

            # Stop generating when model generates end of text token
            if xcol.item() == end_of_text_token:
                break

            x = torch.cat((x, xcol), dim = 1) # Append new token to input to the model
            y = torch.cat((y, xcol), dim = 1) # Append new token to the output

            if x.size(1) > config.context_size: # If x were to grow bigger than the context size, shift out the earliest token
                x = x[:, 1:]

    tokens = y[0, :].tolist()

    if is_training:
        model.train()
    
    return tokenizer.decode(tokens)


if __name__ == '__main__':
    model = load_model('../data/lm.pth')
    
    prompt = f'{end_of_text}Answer this question: What is a car?'
    text = generate(model, prompt)

    print(f'\n{prompt}{text}\n')
